"""create voice_sample table

Revision ID: dbdc7c3a8d4a
Revises: c18030ac1026
Create Date: 2026-08-15 17:22:48.767443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdc7c3a8d4a'
down_revision: Union[str, Sequence[str], None] = 'c18030ac1026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_profile_id', sa.Integer(), nullable=False),
    sa.Column('storage_reference', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_samples')
    # ### end Alembic commands ###
