from typing import Protocol

from .organization_models import CreateOrganization, Organization
from .user_models import CreateUser, User
from .voice_profile_models import CreateVoiceProfile, VoiceProfile
from .voice_sample_models import CreateVoiceSample, VoiceSample


class OrganizationRepository(Protocol):
    async def get_list(self) -> list[Organization]: ...
    async def get_by_id(self, id: int) -> Organization | None: ...
    async def add(self, request: CreateOrganization) -> Organization: ...
    async def upgrade(self, id: int, request: CreateOrganization) -> Organization | None: ...
    async def remove(self, id: int) -> None: ...

class UserRepository(Protocol):
    async def get_list(self) -> list[User]: ...
    async def get_by_id(self, id: int) -> User | None: ...
    async def add(self, request: CreateUser) -> User: ...
    async def upgrade(self, id: int, request: CreateUser) -> User | None: ...
    async def remove(self, id: int) -> None: ...
    async def organization_existing(self, id: int) -> bool: ...

class VoiceProfileRepository(Protocol):
    async def get_list(self) -> list[VoiceProfile]: ...
    async def voice_profile_existing(self, id: int) -> bool: ...
    async def get_by_organization_id(self, organization_id: int) -> list[VoiceProfile]: ...
    async def add(self, request: CreateVoiceProfile) -> VoiceProfile: ...
    async def upgrade(self, id: int, request: CreateVoiceProfile) -> VoiceProfile | None: ...
    async def remove(self, id: int) -> None: ...
    async def organization_existing(self, id: int) -> bool: ...

class VoiceSampleRepository(Protocol):
    async def get_list(self) -> list[VoiceSample]: ...
    async def get_by_voice_profile_id(self, voice_profile_id: int) -> list[VoiceSample]: ...
    async def add(self, request: CreateVoiceSample) -> VoiceSample: ...
    async def upgrade(self, id: int, request: CreateVoiceSample) -> VoiceSample | None: ...
    async def remove(self, id: int) -> None: ...
    async def voice_profile_existing(self, id: int) -> bool: ...
    async def voice_sample_existing(self, id: int) -> bool: ...
